# --- Site settings ---
title: "Yunzhi Lin"
email: yunzhi.lin@berkeley.edu
description: >-
  Bioengineering student at UC Berkeley. I build useful things at the intersection of manufacturing, simulation, and human centered design.
twitter_username:
github_username: lin-yunzhi

# User sites publish at the root, so leave baseurl empty and set url to your username site
url: "https://lin-yunzhi.github.io"
baseurl: ""

# Visual style
minimal_mistakes_skin: default   # try: air, aqua, contrast, dark, dirt, mint, neon, plum, sunrise

# Search
search: false

# Hide feed
atom_feed:
  hide: true

# --- Build settings ---
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.27.3"   # pin for stability
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: "America/Los_Angeles"

include:
  - _pages

# --- Plugins (GitHub Pages supported) ---
plugins:
  - jekyll-remote-theme     # required for remote_theme on Pages
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Helpful for site.github.* data and canonical URLs
repository: "lin-yunzhi/lin-yunzhi.github.io"

# --- Author profile (sidebar card) ---
author:
  name   : "Yunzhi Lin"
  avatar : "/assets/images/yunzhi-lin-photo.jpg"   # replace with a real image
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:yunzhi.lin@berkeley.edu"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/yunzhi-l/"

# --- Defaults ---
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# --- Archives ---
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
